### ISSUE TITLE
_next folder return 404 error

### ISSUE THREAD

**Issue by NaveenDA** [thierryc/Next-gh-page-example#10]
<img width="786" alt="Screenshot 2020-10-13 at 6 41 58 PM" src="https://user-images.githubusercontent.com/20555082/95865049-d3c96480-0d83-11eb-9350-e094e558991d.png">

**Comment by thierryc** [comment]
thank you to report it. I will fix it.

**Comment by NaveenDA** [comment]
Hi @thierryc ,
I fix this issue in my portfolio by setting the  `assetPrefix`
https://naveenda.github.io/
```js 
const isProd = process.env.NODE_ENV === 'production'

module.exports = {
  // Use the CDN in production and localhost for development.
  assetPrefix: isProd ? 'https://raw.githubusercontent.com/NaveenDA/naveenda.github.io/gh-pages/' : '',
}
```

**Comment by wilgnne** [comment]
This is due to the pre-processing of jekyll, which ignores all folders with a `_` prefix, to resolve it, just add a `.nojekyll` file, to the directory containing the `_next` folder, in this case in the gh-pages root.

**Comment by wilgnne** [comment]
This can also be done in the CI process, with just a `touch out/.nojekyll` after `next export`.
