### ISSUE TITLE
Add a .nojekyll file in gh-pages branch 

### ISSUE THREAD

**Issue by timtorChen** [thierryc/Next-gh-page-example#3]
I found the example repo got the same issue as I just faced. Github pages is powered by Jekyll, and Jekyll do not serve any folder start with `_` , as the result we got 404 when loading any resource in `_next` folder. Maybe you can resolve the error by adding a `.nojekyll` file in  gh-pages branch. 

![image](https://user-images.githubusercontent.com/29598693/75372881-28f35b80-5904-11ea-9a69-d1f6444bc556.png)

**Comment by jamesplease** [comment]
This issue is resolved by #5
